# Generated by Django 3.0.1 on 2020-04-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chalenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalenge', models.CharField(max_length=300)),
                ('result', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=300)),
                ('heure', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lampe', 'Lampe'), ('Prise', 'Prise'), ('Rideau', 'Rideau')], max_length=255)),
                ('commande', models.CharField(max_length=255)),
                ('commande2', models.CharField(blank=True, max_length=255, null=True)),
                ('commande3', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='chambres.Chambre')),
            ],
        ),
    ]
